steps:
  # This is a hacky step in order to allow the common tools to use itself to test itself
  - label: Generate generic checks for self
    command: ./common/pipelines/generic_checks.sh --tools-plugin-version $BUILDKITE_COMMIT

  - label: Run argbash and ensure no changes haven't been generated
    command: ./common/scripts/argbash_check.sh common/

  - label: Test pipeline generation is generating valid YAML
    command:
      - ./tests/yamllint.sh

  - label: Test build_tag_push_image.sh
    command: >
      ./common/scripts/build_tag_push_image.sh
      --no-push
      --docker-build-arg TEST1_ARG=testvalue
      --docker-build-arg TEST2_ARG=testvalue
      --build-image-tag test
      not-a-real-docker-repo
      tests/fake-docker-project/Dockerfile
      tests/fake-docker-project/
